### ISSUE TITLE
VMSS Error - KeyError: 'dnsSettings'

### ISSUE THREAD

**Issue by gbuckmaster** [msleal/asciivmssdashboard#7]
I'm getting this error consistently when trying to query an active VMSS.  I've got a proper SP set up for the environment and the json file is populated properly.  

2020-05-26 10:35:56,568 - ERROR:Getting VMSS Information...
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/asciivmssdashboard/azure.py", line 459, in get_vmss_properties
    fill_vmss_info(window_information, vmssget, net);
  File "/usr/local/lib/python3.8/dist-packages/asciivmssdashboard/azure.py", line 314, in fill_vmss_info
    (name, capacity, location, offer, sku, provisioningState, dns, ipaddr) = set_vmss_variables(vmssget, net);
  File "/usr/local/lib/python3.8/dist-packages/asciivmssdashboard/azure.py", line 399, in set_vmss_variables
    dns = net['value'][0]['properties']['dnsSettings']['fqdn'];
KeyError: 'dnsSettings'

**Comment by msleal** [comment]
Hi!
Glad you are trying the ASCiiVMSSDashboard tool! 
The error seems to be DNS (resolution error) and not related to the tool. Maybe the name of the VMSS resource (HOST) or the DNS settings on the specific machine you are trying to run the tool, but from what I can see in the above logs I am not able to relate it to the tool. If you have any other info, please share and I will promptly look into it. Thanks!
